[tool.poetry]
name = "job-search-db"
version = "0.1.0"
description = ""
authors = ["Natalya Sorokina <natali83911@gmail.com>"]
readme = "README.md"
packages = [
    { include = "config.py", from = "src" },
    { include = "db_manager.py", from = "src" },
    { include = "hh_api.py", from = "src" },
    { include = "utils.py", from = "src" },
    { include = "company.py", from = "src" },
    { include = "vacancy.py", from = "src" },
]

[tool.poetry.dependencies]
python = ">=3.12"
requests = ">=2.32.4,<3.0.0"
psycopg2-binary = ">=2.9.10,<3.0.0"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.lint.dependencies]
flake8 = "^7.3.0"
mypy = "^1.16.1"
black = "^25.1.0"
isort = "^6.0.1"

[tool.poetry.group.dev.dependencies]
types-requests = "^2.32.4.20250611"
types-psycopg2 = "^2.9.21.20250516"

[tool.mypy]
disallow_untyped_defs = true
no_implicit_optional = true
warn_return_any = true
exclude = 'venv'

[tool.black]
line-length = 119
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | dist
)/|foo.py
'''

[tool.isort]
line_length = 119
